- 8.Screen-Sharing/Screen-Sharing/Screen-Sharing-Info.plist
- 8.Screen-Sharing/Screen-Sharing/TBScreenCapture.m
- 8.Screen-Sharing/Screen-Sharing/ViewController.m
Reverts opentok/opentok-ios-sdk-samples#63
> Revert "Publish audio, and add subscriber."

- 8.Screen-Sharing/Screen-Sharing/Base.lproj/Main_iPad.storyboard
- 8.Screen-Sharing/Screen-Sharing/Base.lproj/Main_iPhone.storyboard
Reverts opentok/opentok-ios-sdk-samples#64
> Revert "Add iPad story board"

- 1.Hello-World/Hello-World.xcodeproj/project.pbxproj
- 2.Lets-Build-OTPublisher/Lets-Build-OTPublisher.xcodeproj/project.pbxproj
- 3.Live-Photo-Capture/Live-Photo-Capture.xcodeproj/project.pbxproj
- 4.Overlay-Graphics/Overlay-Graphics.xcodeproj/project.pbxproj
- 5.Multi-Party-Call/Multi-Party-Call.xcodeproj/project.pbxproj
- 6.Audio-Levels/Audio-Levels.xcodeproj/project.pbxproj
- 7.External-Audio-Device/External-Audio-Device.xcodeproj/project.pbxproj
- 7.External-Audio-Device/External-Audio-Device/MyAudioDevice.m
- 8.Screen-Sharing/Screen-Sharing.xcodeproj/project.pbxproj
fix audio route/interruption handlers.
save and restore audio session category.
> Update projects to link against libc++ and libicucore. 2.4.0

- 1.Hello-World/Hello-World.xcodeproj/project.pbxproj
- 2.Lets-Build-OTPublisher/Lets-Build-OTPublisher.xcodeproj/project.pbxproj
- 3.Live-Photo-Capture/Live-Photo-Capture.xcodeproj/project.pbxproj
- 4.Overlay-Graphics/Overlay-Graphics.xcodeproj/project.pbxproj
- 5.Multi-Party-Call/Multi-Party-Call.xcodeproj/project.pbxproj
- 6.Audio-Levels/Audio-Levels.xcodeproj/project.pbxproj
- 7.External-Audio-Device/External-Audio-Device.xcodeproj/project.pbxproj
- 8.Screen-Sharing/Screen-Sharing.xcodeproj/project.pbxproj
- 9.OTMoviePlayer/OTMoviePlayer.xcodeproj/project.pbxproj
* Remove libxml2 dependency
* Use standard architectures; no need to override any more
> MODIFY Project configuration

- 7.External-Audio-Device/External-Audio-Device/OTDefaultAudioDevice.m
> OPENTOK-29304 - Fix audio code

- Custom-Video-Driver/Lets-Build-OTPublisher/TBExampleVideoCapture.m
Reverts opentok/opentok-ios-sdk-samples#186
> Revert "Fixes: Main Thread Checker: UI API called on a background thread"

- OpenTokSDKVersion.rb
> Update iOS SDK to latest 2.16.3

- OpenTokSDKVersion.rb
> Update pod files to 2.16.3

- Custom-Video-Driver/Lets-Build-OTPublisher/Single-Cam-Capturer/TBExampleVideoCapture.h
- Custom-Video-Driver/Lets-Build-OTPublisher/Single-Cam-Capturer/TBExampleVideoCapture.m
- FrameMetadata/FrameMetadata.xcodeproj/xcshareddata/xcschemes/FrameMetadata.xcscheme
- FrameMetadata/FrameMetadata.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- FrameMetadata/FrameMetadata/Base.lproj/Main_iPhone.storyboard
- FrameMetadata/FrameMetadata/FrameMetadata.plist
- FrameMetadata/FrameMetadata/ViewController.m
https://github.com/opentok/opentok-ios-sdk-samples/issues/210
> Added code to showcase subscriber frame metadata. 

- OpenTokSDKVersion.rb
[OPENTOK-41638: Update iOS SWIFT samples to use 2.18](https://tokbox.atlassian.net/browse/OPENTOK-41638)
> OPENTOK-41638: Update iOS samples to use 2.18

- Screen-Sharing/Podfile
- Screen-Sharing/Screen-Sharing.xcodeproj/project.pbxproj
- Screen-Sharing/Screen-Sharing.xcodeproj/xcshareddata/xcschemes/Screen-Sharing.xcscheme
- Screen-Sharing/Screen-Sharing.xcworkspace/contents.xcworkspacedata
- Screen-Sharing/Screen-Sharing.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
I moved the min ios version to ios 12, cleaned up all the project warnings and deprecations that arose too.
PR relies on #220, review the latest commit
> update screen sharing

- Custom-Video-Driver/Custom-Video-Driver.xcodeproj/project.pbxproj
- Custom-Video-Driver/Custom-Video-Driver.xcodeproj/xcshareddata/xcschemes/Custom-Video-Driver.xcscheme
- Custom-Video-Driver/Custom-Video-Driver.xcworkspace/contents.xcworkspacedata
- Custom-Video-Driver/Custom-Video-Driver.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Custom-Video-Driver/Lets-Build-OTPublisher/Images.xcassets/Contents.json
- Custom-Video-Driver/Lets-Build-OTPublisher/Single-Cam-Capturer/TBExampleVideoCapture.m
- Custom-Video-Driver/Lets-Build-OTPublisher/TBExampleVideoRender.m
- Custom-Video-Driver/Podfile
I moved the min ios version to ios 12, cleaned up all the project warnings and deprecations that arose too.
PR relies on #220, review the latest commit
> update custom video driver

- Overlay-Graphics/Overlay-Graphics.xcodeproj/project.pbxproj
- Overlay-Graphics/Overlay-Graphics.xcodeproj/xcshareddata/xcschemes/Overlay-Graphics.xcscheme
- Overlay-Graphics/Overlay-Graphics.xcworkspace/contents.xcworkspacedata
- Overlay-Graphics/Overlay-Graphics.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Overlay-Graphics/Podfile
I moved the min ios version to ios 12, cleaned up all the project warnings and deprecations that arose too.
PR relies on #221, review the latest commit
> update overlay graphic

- Audio-Levels/Audio-Levels.xcodeproj/project.pbxproj
- Audio-Levels/Audio-Levels.xcodeproj/xcshareddata/xcschemes/Audio-Levels.xcscheme
- Audio-Levels/Audio-Levels.xcworkspace/contents.xcworkspacedata
- Audio-Levels/Audio-Levels.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Audio-Levels/Podfile
I moved the min ios version to ios 12, cleaned up all the project warnings and deprecations that arose too.
PR relies on #221, review the latest commit
> update audio levels

- Custom-Audio-Driver/External-Audio-Device/OTDefaultAudioDevice.m
Looks like the iOS 14 compact/full screen mode takes some time to give up audio settings
refer https://stackoverflow.com/questions/26759942/ios-audiounitinitialize-returns-error-code-561017449 for the error we are seeing.
I  turned on the debug flag by default as this is an Audio Driver sample and we better show as many logs as we can, by default
The retry count has been bumped up to 5 from 3 , as losing audio is a big thing in a session, so we try our best.
> Added retry mechanism (like recording) for player mode of audio unit

- Custom-Video-Driver/Lets-Build-OTPublisher/Multi-Cam-Capturer/TBExampleMultiCamCapture.m
- Custom-Video-Driver/Lets-Build-OTPublisher/Single-Cam-Capturer/TBExampleVideoCapture.m
Fixes typo of "Capurer" to "Capturer"
> Capturer typo fix in error message

- Basic-Video-Chat-XCFramework/Basic-Video-Chat.xcodeproj/project.pbxproj
- Basic-Video-Chat-XCFramework/Basic-Video-Chat.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Basic-Video-Chat-XCFramework/Basic-Video-Chat.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Basic-Video-Chat-XCFramework/Basic-Video-Chat.xcodeproj/xcshareddata/xcschemes/Basic-Video-Chat.xcscheme
- Basic-Video-Chat-XCFramework/Basic-Video-Chat.xcworkspace/contents.xcworkspacedata
- Basic-Video-Chat-XCFramework/Basic-Video-Chat.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/AppDelegate.h
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/AppDelegate.m
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/Base.lproj/Main_iPad.storyboard
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/Base.lproj/Main_iPhone.storyboard
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/Images.xcassets/AppIcon.appiconset/Contents.json
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/Images.xcassets/Contents.json
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/Info.plist
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/ViewController.h
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/ViewController.m
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/en.lproj/InfoPlist.strings
- Basic-Video-Chat-XCFramework/Basic-Video-Chat/main.m
- Basic-Video-Chat-XCFramework/Podfile
- Basic-Video-Chat-XCFramework/README.md
Add sample app for XCFramework
[OPENTOK-44181](https://jira.vonage.com/browse/OPENTOK-44181)
This PR is depends of the approval of a new cocoapod repository: https://github.com/opentok/native-sdk-src/pull/3409
> OPENTOK-44181: Add sample app for XCFramework

- Basic-Video-Chat-XCFramework/README.md
Include comment about OTXCFramework version
> update readme file

- Custom-Video-Driver/Lets-Build-OTPublisher/Multi-Cam-Capturer/TBExampleMultiCamCapture.m
- Custom-Video-Driver/Lets-Build-OTPublisher/Single-Cam-Capturer/TBExampleVideoCapture.m
- Screen-Sharing/Screen-Sharing/TBScreenCapture.m
- Screen-Sharing/Screen-Sharing/ViewController.m
The screen sharing app shows how to use it
> Content hint synthesize added

- Custom-Audio-Driver/External-Audio-Device/OTDefaultAudioDevice.m
Sync of sample code  with SDK code
> OPENTOK-46715: iOS Custom Audio Driver sync with SDK implementation

- OpenTokSDKVersion.rb
Hi, Opentok version is updated using 2.25.0 in this pr
> VIDCS-735: Update OPENTOK version on iOS samples

- OpenTokSDKVersion.rb
> VIDCS-1158: Update version to 2.25.3

- OpenTokSDKVersion.rb
Update iOS sample apps to SDK v2.27.0
> Update to v2.27.0

- Custom-Audio-Driver/Custom-Audio-Driver.xcodeproj/project.pbxproj
- Custom-Audio-Driver/External-Audio-Device/OTDefaultAudioDevice.m
- Custom-Audio-Driver/External-Audio-Device/OTDefaultAudioDevice.mm
> VIDSC-584: Changed default Audio Driver to reflect the 2.29 SDK audio SDK code
